### ISSUE TITLE
不知道能不能添加一个快捷键热切换播放速度的功能呢

### ISSUE THREAD

**Issue by 745835880** [yk0n9/lyred#3]
请问一下能不能添加一个快捷键热切换播放速度的功能呢，我在之前有帮忙测试vrchat中文吧的键位，但是后来好像失去了联系方式

**Comment by yk0n9** [comment]
实施 #4 

请重新下载[latest release](https://github.com/ykong1337/lyred/releases/download/1.2/lyred.exe)

**Comment by 745835880** [comment]
辛苦了，感谢~
